### ISSUE TITLE
#1 Add Item to My Items US 01.01.01

### ISSUE THREAD

**Issue by beylulari** [CMPUT301F23T17/SweetHome#1]
**As an owner, I want to add an [item](https://github.com/CMPUT301F23T17/SweetHome/wiki/Product-Backlog-Part-2#items) to my items, with a date of purchase or acquisition, brief description, make, model, serial number (if applicable), estimated value, and comment.**

This is an essential function for the application. This US suggests that:
> As an owner, I want to simply click a button to add a new item.

> As an owner, I want to be notified if an item I am adding is missing necessary details such as the date of purchase or acquisition, brief description, make, model, and estimated value.

**Comment by TonyPhan0505** [comment]
This issue, issue #2 and issue #3 are solved simultaneously in the branch [2-view-an-item-and-its-details-us-010201](https://github.com/CMPUT301F23T17/SweetHome/tree/2-view-an-item-and-its-details-us-010201).
