### ISSUE TITLE
#2 View an Item and Its Details US 01.02.01

### ISSUE THREAD

**Issue by PaulCleofas** [CMPUT301F23T17/SweetHome#2]
**As an owner, I want to view an [item](https://github.com/CMPUT301F23T17/SweetHome/wiki/Product-Backlog-Part-2#items) and its details.**

This is an essential function for the application. This US suggests that:
> As an owner, I want to simply click on an item and see its details.

> As an owner, I want to see the details of an item in a clearly labelled but aesthetically pleasing layout.

**Comment by TonyPhan0505** [comment]
This issue, issue #1 and issue #3 are solved simultaneously in the branch [2-view-an-item-and-its-details-us-010201](https://github.com/CMPUT301F23T17/SweetHome/tree/2-view-an-item-and-its-details-us-010201).
