### ISSUE TITLE
#3 Edit Item Details US 01.03.01

### ISSUE THREAD

**Issue by beylulari** [CMPUT301F23T17/SweetHome#3]
**As an owner, I want to edit the details of an [item](https://github.com/CMPUT301F23T17/SweetHome/wiki/Product-Backlog-Part-2#items).**

This is an essential function of the application. This US suggests that:
> As an owner, I want to be able to update the details of an item at any time.

> As an owner, I want to have the option to discard or confirm the changes I make to an item.

> As an owner, I want to be notified if the changes I attempt make to an item cause the item to be missing any necessary details.

**Comment by TonyPhan0505** [comment]
This issue, issue #1 and issue #2 are solved simultaneously in the branch [2-view-an-item-and-its-details-us-010201](https://github.com/CMPUT301F23T17/SweetHome/tree/2-view-an-item-and-its-details-us-010201).
